### ISSUE TITLE
node-sass一直安装不上

### ISSUE THREAD

**Issue by Hbuilderx** [JS-Encoder/JS-Encoder#25]
你是用的是哪个npm版本，现在node-sass一直安装不上，很头疼，我用的M1芯片的MacBook pro

**Comment by Longgererer** [comment]
请问有安装报错的截图么？如果是版本不兼容的问题，我想你可以通过以下两种办法解决这个问题：

1. 升级node-sass版本。
2. 降低node版本。

版本可参照下图：

![image](https://user-images.githubusercontent.com/40834209/163769847-5fdffd49-446b-4e79-bf18-15e80b03ca56.png)

**Comment by Hbuilderx** [comment]
我看你有个升级后了node-sass的分支，我先试试这个

**Comment by Hbuilderx** [comment]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/38787896/163794687-48733678-b53a-4ece-ae9f-c8620f841dfd.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/38787896/163794739-f04bc2c3-c792-49fb-9f81-83ea86be11a4.png">
新的好像也不行

**Comment by Longgererer** [comment]
从控制台的信息看来并不是node与node-sass的版本冲突问题，而是node-sass不支持你的系统架构arm64。

你可以卸载 `npm uninstall node-sass` 并使用 `npm install sass` 来代替。

**Comment by Hbuilderx** [comment]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/38787896/163797096-4216bf01-8368-48a0-bc42-b5f748360af2.png">
<img width="407" alt="image" src="https://user-images.githubusercontent.com/38787896/163797130-0d206686-5056-492e-b44d-d6b8083e60d9.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/38787896/163797257-cc895ee9-46de-4aad-93b1-aa92e0b5fcbb.png">

我换成了sass，实在搞不了node-sass了，之前就是被node-sass搞得很烦
另外/deep/语法需要换成::v-deep

不过还是谢谢你能及时回应

**Comment by Longgererer** [comment]
哈哈不客气
