### ISSUE TITLE
请问一下作者有计划使用vite+vue3+codemirror6重构项目的计划吗

### ISSUE THREAD

**Issue by soup-Lee** [JS-Encoder/JS-Encoder#32]
我最近在尝试使用codemirror6开发一个编译器，您的项目给了我很多的启发，但是想达到您的高度太难了，请问有计划使用新的技术去进行重构吗？想学习学习

**Comment by Longgererer** [comment]
Hello，很高兴看到你的提问！

**Comment by Longgererer** [comment]
Hello，很高兴看到你的提问！
我已经开始使用 vite+vue3+codemirror6 重构项目了，并且会在新的大版本中加入更多的新功能。只是最近由于工作原因，进展较慢，但我会全力以赴。
如果你有什么问题的话，欢迎一起讨论哈！
wx: lliio-_-oiill
