### ISSUE TITLE
大佬 下载代码的功能是我不会用还是有bug 一直下载错误

### ISSUE THREAD

**Issue by 2016011969sunyifang** [JS-Encoder/JS-Encoder#41]
每次下载都会下载一些模版 而非我的代码 
大佬可以留个联系方式么  求教

**Comment by Longgererer** [comment]
好的好的，我微信号：lliio-_-oiill

**Comment by Longgererer** [comment]
> 每次下载都会下载一些模版 而非我的代码 大佬可以留个联系方式么 求教
@2016011969sunyifang

**Comment by Longgererer** [comment]
> 每次下载都会下载一些模版 而非我的代码 大佬可以留个联系方式么 求教

@2016011969sunyifang 好的好的，我微信号：lliio-_-oiill

**Comment by SpiritBreaker** [comment]
我本地部署后，没搜到创建实例相关的代码啊？

**Comment by Longgererer** [comment]
> 我本地部署后，没搜到创建实例相关的代码啊？

有疑问请创建新的issue谢谢
