### ISSUE TITLE
是否会考虑增加vue的单文件模板

### ISSUE THREAD

**Issue by Azir-11** [JS-Encoder/JS-Encoder#58]
是否会考虑支持类型这样的写法：
``` vue
<script setup>
import {ref} from 'vue'
const message = ref("hello")
</script>

<template>
  <div>
    {{ message }}
  </div>
</template>
```

**Comment by Longgererer** [comment]
目前可以支持这样的写法，在模板中选择标识有 Component（代表单文件组件）的 Vue 模板：

<img width="532" alt="image" src="https://github.com/JS-Encoder/JS-Encoder/assets/40834209/edbf5fc0-b640-4ad3-a864-c70aa31c9136">

即可使用上述写法，点击[链接](https://www.jsencoder.cn/code?config=eNpVUMFqwzAM%2FRWjSzcI8aE7hWxQctnGCmMpvSw9OImSuji2sZWyEfLvs5Mx1ov1HvJ7kt4EjWlxLyxkE7zujruy%2BHh5P0AGuW%2BctMQ80mifKi0HaxyxyWE3s86ZgW2uI24q3RjtiQ3oveiRPbLw4a6CMyplKrivdM5Xp%2BARCOFglSCMjPJWXhdQ0TT9Wczz0uNrM%2Bf%2FJDAngK0k4wqjO9nHrZWsnXASfSSevhVC9nlKYJ0aMJyJrM84b1qd1sZQrBqJi4v44kHuebiEb9Nt%2BhBR2itTC5UOUqcXD6cw0zq0vyE9H%2FZvIZ6lJFCUZSDxTW7jO44Ic1BKX5iQnEYdViE34vwDr91%2FQQ%3D%3D)查看效果。

**Comment by Azir-11** [comment]
好的，疏忽了😂，感谢🙏🙏🙏
