### ISSUE TITLE
在使用script setup语法糖的块内，回车总会多出一个缩进

### ISSUE THREAD

**Issue by Azir-11** [JS-Encoder/JS-Encoder#62]
**问题描述**
在script setup的单文件模板内些代码的时候，回车换行会带出一层缩进
![image](https://github.com/JS-Encoder/JS-Encoder/assets/79054161/3c349b00-da8f-4439-9510-ca92222f525b)

**如何复现？**
1. 选择vue的component模板，改成setup语法糖
2. 正常换行输入

**预期结果是什么？**
光标应该定位到行首
**浏览器版本**
Microsoft Edge
版本 126.0.2592.61 (正式版本) (64 位)
**其他内容**

**Comment by Longgererer** [comment]
已复现。

@codemirror/lang-vue 可以让 codemirror 支持 vue 语法；已知原因是：@codemirror/lang-vue 基于 @codemirror/lang-html 进一步实现对 vue 的支持，**因此大部分行为（如缩进）与 html 是相同的**，html 中 script 标签内的代码会默认缩进一个单元。

我会想办法修改配置看能否解决。

**Comment by Longgererer** [comment]
该问题已在 #63 中修复
